name: Flutter CI

on:
  push:
    branches:
      - tutorial-001-base-ui-complete

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
          flutter-version: '2.8.0'  # Replace with the desired Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

